# Generated by Django 3.1.5 on 2021-01-28 15:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('link', models.CharField(default='', max_length=1000)),
                ('rss', models.CharField(default='', max_length=1000)),
                ('avatar', models.CharField(default='', max_length=1000)),
            ],
            options={
                'db_table': 'sources',
            },
        ),
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=1000)),
                ('link', models.CharField(default='', max_length=1000)),
                ('description', models.CharField(default='', max_length=1000)),
                ('content', models.TextField(default='')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('crawl_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_name', models.CharField(default='', max_length=100)),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sources')),
            ],
            options={
                'db_table': 'entries',
            },
        ),
    ]
